[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = []
optimizer = true
optimizer_runs = 20000
solc_version = "0.8.21"
evm_version = "paris"
via_ir = true

[profile.zksync]
src = 'src'
libs = ['lib']
solc-version = "0.8.21"
fallback_oz = true
is_system = false
mode = "3"

# See more config options https://github.com/gakonst/foundry/tree/master/config

[rpc_endpoints]
lens-testnet = "https://rpc.testnet.lens.dev"
lens = "https://rpc.lens.dev"